### ISSUE TITLE
Need Some help

### ISSUE THREAD

**Issue by hemwahdan** [deltaxflux/fluxion#268]
AWUS036H  RTL8187L problem with fake page , it's so slow  fakepage  speed 4kb
but when i tried with AR9271 and AR9285 it's work fine and speed  above 200kb
sorry for bad English

**Comment by deltaxflux** [comment]
The wireless card is unsupported

**Comment by hemwahdan** [comment]
Thanks :)

**Comment by hemwahdan** [comment]
@deltaxflux , I wanna support list please

**Comment by deltaxflux** [comment]
Such a list already exist: 
https://www.aircrack-ng.org/doku.php?id=compatibility_drivers

**Comment by strasharo** [comment]
The driver used for  RTL8187L is not compatible with hostapd, which leaves the only option to work with airbase-ng in order to create the access point (there's an explicit rule to do that in fluxion). And as your experience shows, airbase-ng is really slow compared to hostapd. If you need performance, better choose an adapter which is compatible with hostapd and is able to inject.
