### ISSUE TITLE
captive portal Not Starting

### ISSUE THREAD

**Issue by naflan121** [deltaxflux/fluxion#28]
Everything work well. as soon as the evil ap is created and a victim is joined, the webpage is not redirected to captive portal or captive portal not start the page says "ERR_CONNECTION_FAILD"

**Comment by aliwaqas2323** [comment]
does your evil ap is creating mine one is not there is no fake ap

**Comment by naflan121** [comment]
what wifi adapter you use?

**Comment by aliwaqas2323** [comment]
intel centrino advanced n 6200 agn and what wifi adapter You use?

**Comment by naflan121** [comment]
prefer to user a external wifi adapter

**Comment by aliwaqas2323** [comment]
which wifi adapter are  you using?

**Comment by deltaxflux** [comment]
@aliwaqas2323 a external wifi card is recommend because the intel centrino advanced n 6200 agn support captching packets partly.
@naflan121 if you need help send me a massage 

The **issues Bord** is not a _help desk_. It is a Bord for **_real_** Issues 

**Please read the requirements** _(ReadME.md)_
