### ISSUE TITLE
Problem with DHCP

### ISSUE THREAD

**Issue by Flavius992** [deltaxflux/fluxion#299]
### Which version of fluxion are you using?
<0.23>

### What distribution of Linux (including the version) are you running it on?
<Ubuntu 16.04 LTS>

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
<Qualcomm Atheros QCA9565 / AR9565 Wireless Network Adapter>

### Which is the driver for it?
<driver=ath9k driverversion=4.4.0-53-generic>

### Does it support injection ( output of aireplay-ng -9)
<Injection is working!>

### General description of your issue along with the steps to reproduce it
<After the handshake and start attack with Web interfaces, it start fake AP, FAKEDNS, Deathall [mdk3] and WifiInformation in XTerm windows but not dhcp service! Obviously it's already installed and updated at the last version. How can I resolve this problem?>
![schermata del 2016-12-07 23-07-19](https://cloud.githubusercontent.com/assets/12383848/20988777/7df7d498-bcd2-11e6-8b96-03e29cf90f3c.png)

**Comment by matty0005** [comment]
I'm having the same problem.

**Comment by deltaxflux** [comment]
Well in general the problem is maybe that you have a incompatible dhcp version, but it doesn't matter because you use a incompatible script because I don't think that the chip support master mode. If you look for a cheap external wireless card use the tp-link 722n. 

@matty0005 the leases file is empty untile someone connect. Please note that it is better to make a new issue with your specs because it is easier to handle for me.

**Comment by Flavius992** [comment]
I've read that dhcpd-server packet has been replaced by isc-dhcp-server. Could this be the reason why the dhcp service will not start?

**Comment by deltaxflux** [comment]
I don't think that's the problem

**Comment by matty0005** [comment]
i'm sure other wifi devices work, other than the ones you have tested. I strongly beleive it is a software fault along the line. i am confident these chips will work - just maybe a bit of tweaking.

@deltaxflux The only difference between us two is my physical device. which is Qualcomm Atheros AR9285. and i made a post but you just said "Use a compatible wireless card".

**Comment by matty0005** [comment]
Well, i Installed Kali, and Everything seemed to work. I think it works partially because of the differences in Permissions in kali. 
And @deltaxflux The other day, you said that the AR9285 wouldnt work, and it was incompatible. Well i have just proven you wrong.

**Comment by ImAWizardLizard** [comment]
rekt

**Comment by deltaxflux** [comment]
@matty0005 

> i am confident these chips will work - just maybe a bit of tweaking.

Well in most cases internal chips dosen't work.  Are you shure that it support master mode?

**Comment by matty0005** [comment]
Well, mine seemed to work which you didnt think it would.
@Flaviuz992 try running kali. That may work. You can always make a second partition on your drive and install kali on that.

Otherwise. @deltaflux it could be the fact that you need to allow all users to open/edit some of the dhcpd files. Dhcpd.leases, been one of them. 
Its simply just permissions. The reason it works for me on kali and not ubuntu, is because the default user has root perms. And therefore allows everything as root. Where as ubuntu doesnt seem to run everything as root. Even though you use sudo at the start.

**Comment by deltaxflux** [comment]
`The reason it works for me on kali and not ubuntu, is because the default user has root perms`
defuq, this is one of the things why I hate ubuntu
Anyway there is no point why people shut edit the empty dhcp.leases file
