### ISSUE TITLE
No Android Sign In After Connecting to fakeAP

### ISSUE THREAD

**Issue by jratienza** [deltaxflux/fluxion#306]
### Which version of fluxion are you using?
V 0.23 Rev105
### What distribution of Linux (including the version) are you running it on?
Kali Linux Rolling 2.0

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
TPLINK WN722N
### Which is the driver for it?
Atheros

### Does it support injection ( output of aireplay-ng -9)
Injection works!

### General description of your issue along with the steps to reproduce it
I just followed the steps in the tutorial. However sites are not being redirected. I need to type in 192.168.1.1 in the adress bar in order to reach the login page. I also have read that Wireless Network Sign In appears on android phones but it did not appear on my case. I tried connecting two phones to the fakeAP both of them connected but there was no Android Sign In nor web page redirection.

**Comment by vitteloil** [comment]
Same issue here. I'm trying to debug this captive portal behavior from android 4.X.
It seems it makes a request to clients3.google.com/generate_204 and excepts a 204 redirect. 

if this page really makes a 204 -> android things it's connected on internet and won't open the 'Sign in' popup (splash screen)
if this page returns something else (in our case, it returns 200, because it returns de login page) it SHOULD pop up, but it's not happening on my phone.

I spent 3 hours trying to get more documentation about this. I wonder if it's a DNS issue. With the current DNS setup (the python script), fluxion answers that all DNS goes to the machine where it's running. What we could try is to just reply a fake ip for clients3.google.com. However I'm not sure how to do that with the current python script. (should we switch to dnsmasq ??)

**Comment by deltaxflux** [comment]
I don't think so
