### ISSUE TITLE
pacman not found

### ISSUE THREAD

**Issue by bozoweed** [deltaxflux/fluxion#349]
### Which version of fluxion are you using?
0.23 REV 116

### What distribution of Linux (including the version) are you running it on?
KALI LINUX 2016( the laste kali )

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
internal and it working

### Which is the driver for it?
ralink

### Does it support injection ( output of aireplay-ng -9)
yes

### General description of your issue along with the steps to reproduce it
hi the issue is pacman command not found when execute ./arch-install in a terminal on kali linux 2016 thanks you for solved that and you have make a realy great tool thank you very much for that :)

**Comment by rad4day** [comment]
Well, I see you're not familiar with the different linux distributions. ArchLinux is another linux distribution which uses pacman (instead of apt) as package manager. If you're not using ArchLinux (you're definitely not, since you stated you're using kali linux), then you need to **run the normal installer script.**

**Comment by deltaxflux** [comment]
The arch-installer is for the arch distribution.  You need to run  the default installer 
./Installer

**Comment by strasharo** [comment]
![image](https://cloud.githubusercontent.com/assets/3337997/21824033/421035dc-d786-11e6-854b-f67491679bd5.png)
