### ISSUE TITLE
Slow loading page and No Dual bands deauth? 

### ISSUE THREAD

**Issue by OoImmortaloO** [deltaxflux/fluxion#365]
### Which version of fluxion are you using?
118

### What distribution of Linux (including the version) are you running it on?
Kali 2 

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
RTL8187 Model AWUS036H

### Which is the driver for it?
rtl8187

### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it
I'm testing... on my network see how good is this program works. Still new to kali :). Well 2 Problems so far. It's WORK Yes - No. Yes Its work for those router don't support 5G or Dual band. I was testing on my router have 2.4gh and 5gh My card i think its only support for the 2.4ghz so i test on the 2.4ghz i get disconnected. No handshake captured. I test on my other router for some reason it's capture handshake no problem.  well even i get disconnected. It's automatic switch me to 5Ghz band so i'm back online in seconds.. Is it the flaws? thats the down side. it's not deauth both bands at same time other wise i think we have to have 2nd adapter to manually deauth the other band so both bands can be down at same time.  hopefully we'll see this update in the futures :)

 2nd thing is... when i tested on other router that don't support 2 bands only support 2.4ghz  everything work fine accept..  The fake login page is loading too slow  take like 15seconds or more to complete loading the page. i did tried both option . when I'm next to the router still takes forever to load. Is it me or that's how its work. lol thanks all

**Comment by deltaxflux** [comment]
Well thank you for your detailed issue report. 5ghz is only rarly supported, there is one with support already  injection but only with driver manipulation. Some basics:
The handshake get only captured if you reconnect to the same network you listen to. In this case it is clear why you can't capture the hanshake. You can test it if you forgot your 5 ghz network. 

If there are more than 1 5ghz card out there I will definetly add 5ghz support.

The 2and problem is weird because the sites should load instantly, take a look at it but I never had this problem

**Comment by OoImmortaloO** [comment]
thanks :+1:
