### ISSUE TITLE
Certificate

### ISSUE THREAD

**Issue by valhacks** [deltaxflux/fluxion#385]
### Which version of fluxion are you using?
0.23

### What distribution of Linux (including the version) are you running it on?
Kali linux (Debian)

### What wireless adapter are you using? Exact model and chipset, statements like "internal" and "was working before" are not helpful at all.
Intel pro 

### Which is the driver for it?
<???>

### Does it support injection ( output of aireplay-ng -9)
Yes

### General description of your issue along with the steps to reproduce it
When i initiate the test in fluxion when clients try connecting to the fake wireless network when they try to feed in the password to their hotspot or wireless network it enters them the opposite way. Is it a problem with certificate chosen or i have to create my own.

**Comment by Intek13x** [comment]
Oh it's not the certifcate error, it happening because of little typo in the fluxion script. 
You can fix it on your own by following these steps.. 
1. Go to the directory where fluxion is installed, then open it in text editor. 
2. Search for the string DIALOG_WEB_DIR_ENG="rtl" , and replace it with DIALOG_WEB_DIR_HE="rtl" . 
3. Save and close the text editor. You're done.
