### ISSUE TITLE
FakeAP shouldn't keep orgin SSID

### ISSUE THREAD

**Issue by pigfromChina** [deltaxflux/fluxion#66]
when two APs using the same SSID and have different passwords,devices can't connect to router without "forget network"
I think new SSID can be foobar_recovery or foobar_security_update

**Comment by deltaxflux** [comment]
If I understand you correctly, the main problem is that the victim can't connect automatically to the Fake AP. The main problem is that the victim don't connect automatically to the fake AP because of the different security aspect. Most Wifis use WPA / 2 and the fake AP don't set any password. 

I don't think that is a good idea
