### ISSUE TITLE
handshake problem

### ISSUE THREAD

**Issue by chanakyacool** [deltaxflux/fluxion#72]
sir actually its to making hacking ,i waited for long time ,
plz help me 
yesterday it maked hand shake but no passward,found ,
soory for my english ,

and one more problem is ,
its not deauth the user .,
and if its deauth the user victim is not redirection to login page 
my os is kali-rolling 2016.1

sir i am practicing it on my own computer ,
i have 2 laptops 
one is connected to my android hotspot and atcker comp is on lan

**Comment by deltaxflux** [comment]
If I understand you correctly deauth clients don't work. The main problem could be that your wifi card doesn't support that, Do you use an external Wifi card ? 

I maybe understand correctly more because your English is too bad. Here what it looks like for me: 
_Fake AP load, clients don't get redirected, isn't fast_

Do you check my HF post? Contact me under: deltax.fluxion@gmail.com, for more help. Please make sure that you tell me your complete setup.
