### ISSUE TITLE
Auto Channel Request

### ISSUE THREAD

**Issue by eduardogt** [deltaxflux/fluxion#89]
There are networks that change channel and the tool stops running. Could put a autochannel? Greetings
Great Job!

**Comment by strasharo** [comment]
We can easily work around this if we make mandatory having a second wireless adapter in order to run fluxion. This way we can leave mdk3 in channel hopping mode in order to chase the network around the full spectrum. However this solution might not be convenient for most of the users who operate on a single card.
The other way around would be to use the VAP capability of Atheros adapters such as TL-WN722N in order to launch an additional virtual interface to do only the deauth, however this way we'll tie the tool to a specific chipset vendor, which will be not convenient for users having non-Atheros chipsets. 
Trying to achieve this behaviour on a single interface without VAP capability is very unreliable and will significantly affect the performance of the tool in a negative way, which we want to avoid.

**Comment by eduardogt** [comment]
Oh great as you did not think this is a genius!
What would be the command to mdk3 to recommend me to follow the spectrum of a specific network?
Thanks

**Comment by strasharo** [comment]
There's no such functionality in mdk3 to "follow" a network. But if you have a separate adapter, which supports injection, you can launch something like this:

mdk3 mon0 d -b /tmp/TMPflux/mdk3.txt

Where in the mdk3.txt you'll have to have the BSSID of the target network. The difference between this and the usage in fluxion is that mdk3 is not locked to a specific channel ( -c switch) but it hops freely across all channels and once it sees traffic matching the blacklist it sends deauthentication requests to the networks that match it.

**Comment by deltaxflux** [comment]
I will maybe remove the channel lock

**Comment by strasharo** [comment]
Don't do that! Since we're running on a single card that will cause the fake AP running around all channels for the setups using airbase-ng.

**Comment by eduardogt** [comment]
Hello strasharo with a second adapter works perfectly. deltaxflux do not do it! The networks that change channel are very few. But as said the good friend and gentle strasharo with a second adapter works. Many thanks!

**Comment by strasharo** [comment]
In fact it's quite common at least according to my observations to have the channel set to "auto" by default, which results in channel changes when the router starts and it's pretty annoying to be monitoring for changes manually. I some ideas about implementing some sort of a heartbeat in order to check and warn the user if the AP is no longer responding on the initial channel. I'll give it a go once I have some free time to play.

**Comment by eduardogt** [comment]
Exactly if the application alert the user channel change would be great.
That would give more power to attack script.
