### ISSUE TITLE
idk what this means

### ISSUE THREAD

**Issue by trumanyardley** [deltaxflux/fluxion#99]
wc: /tmp/TMPflux/dump-01.csv: No such file or directory
./fluxion: line 1154: [: -le: unary operator expected
cat: /tmp/TMPflux/dump-01.csv: No such file or directory
expr: syntax error
                        WIFI LIST 

 ID      MAC                      CHAN    SECU     PWR   WPS ESSID

grep: invalid: No such file or directory
grep: number: No such file or directory
grep: of: No such file or directory
grep: lines:: No such file or directory
grep: ‘/tmp/TMPflux/dump-01.csv’: No such file or directory
  1)	head: invalid number of lines: ‘/tmp/TMPflux/dump-01.csv’	 	   100%

**Comment by strasharo** [comment]
Could you, please, describe what were you doing exactly when you received this error? "idk what this means" is far from being a useful description.

**Comment by trumanyardley** [comment]
I select my interface (wlan0) and all channels and it displays that.

**Comment by strasharo** [comment]
Does your interface support monitor mode and injection?

**Comment by trumanyardley** [comment]
How would I know if it doesn't?

**Comment by devrajashwin** [comment]
i think ur ruining php 7 version cgi ,
if yes it wont work u have to downgrade it to php 5-cgi

**Comment by deltaxflux** [comment]
Yeah , php5-cgi is definitely the problem, not. I think your wificard don't support monitor mode injection, this means it is not a problem by fluxion.

**Comment by theoneandonly-vector** [comment]
how to downgrade php7-cgi to php5-cgi, without breaking other stuff on kali rolling?

**Comment by strasharo** [comment]
There's no need to downgrade to 7, it's already supported, just pull the latest version of fluxion.

**Comment by theoneandonly-vector** [comment]
just pulled the newest version -> still the same error.

**Comment by strasharo** [comment]
What error are you receiving?

**Comment by theoneandonly-vector** [comment]
#########################################################
#                                                       #
#      FLUXION 0.23    < Fluxion Is The Future >        #
# by Deltax, Strasharo and ApatheticEuphoria            #
#                                                       #
#########################################################

wc: /tmp/TMPflux/dump-01.csv: No such file or directory
/opt/fluxion/fluxion: line 1154: [: -le: unary operator expected
cat: /tmp/TMPflux/dump-01.csv: No such file or directory
expr: syntax error
                        WIFI LIST

ID      MAC                      CHAN    SECU     PWR   ESSID

grep: invalid: No such file or directory
grep: number: No such file or directory
grep: of: No such file or directory
grep: lines:: No such file or directory
grep: '/tmp/TMPflux/dump-01.csv': No such file or directory
  1)    head: invalid number of lines:
'/tmp/TMPflux/dump-01.csv'             100%
(*)Active clients
        Select target. For rescan type r
      #>

Am 11.09.2016 11:06 nachm. schrieb "strasharo" <notifications@github.com>:

What error are you receiving?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/deltaxflux/fluxion/issues/99#issuecomment-246204612>,
or mute the thread

**Comment by theoneandonly-vector** [comment]
a little update over here.. I'm on Kali Nethunter.. and there you need to
run it via VNC, because it opens up other terminal windows..
so it only doesn't work through kali-nethunter via
android-terminal-emulator.

**Comment by deltaxflux** [comment]
As I already said

**Comment by C31b0** [comment]
Hi i new here and this is my first post. 
I have the same problem.
Im using Kali last version. I was running fluxion without problems till today.
I have two wireless adapters, one of them onboard my mac air and the other is an Alfa usb. BOTH support monitor mode and both were working till today.
When i run fluxion, i select one of my card, then ¨all channels ( same happens if i select just specific channel ), then the scan starts, when i atop it with ctrl C i get the error:
grep : invalid : no such file or directory
grep : number : no such file or directory
grep : of : no such file or directory
grep : lines : no such files or directory
[1] head : invalid number if lines : ´/tmp/TMPflux/dump-01.csv

And thats it. can't go on.
The last that i did last night was install android emulator. ( that i don't know how to remove to test if its the problem )
Till yesterday, when i type airmon-ng the answer was 
phy 7 wlan0 ( ALFA usb card )
phi 7 wlan1 ( pci internal card )
Now it shows.
phy 7 wlan0 ( pci internal card )
phy 8 wlan1 ( ALFA usb card ) 
Why they are inverted and why phy 8 now instead of 7 just in one of them ?

theoneandonly-vector said : 
a little update over here.. I'm on Kali Nethunter.. and there you need to
run it via VNC, because it opens up other terminal windows..
so it only doesn't work through kali-nethunter via
android-terminal-emulator.

I don't know how to run it via VNC, could someone explain that a little bit ?
THANKS IN ADVANCE !!!!
C31b0
